// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyunoaekpynmcxksjmfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dW5vYWVrcHlubWN4a3NqbWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTk5MzEsImV4cCI6MjA2NDE3NTkzMX0.pqEGBzlO9i8KkJ1gaX2s4NFAYkj52UyMrujSc-KjzXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);